---
title: "DK Pineal2 Day 1 10X Seurat v2"
author: "Joseph Mays"
output:
  html_notebook: default
  html_document: default
  pdf_document: default
---

```{r Pineal2_Day1 Import, results="hide"}
Pineal2_Day1.matrix <- Read10X(data.dir = "../Results/Day1/filtered_gene_bc_matrices/Rnor6.0.90_10X/")
Pineal2_Day1 <- CreateSeuratObject(Pineal2_Day1.matrix, project = "Pineal2_Day1", min.cells = 3, min.genes = 800)
#11 cells have less than 800 genes
Pineal2_Day1 <- MetaDataInit(Pineal2_Day1, ID.prefix = "Day1")
```

```{r QC stats}
Pineal2_Day1
Pineal2_Day1.mito.genes <- grep("^Mt-", rownames(Pineal2_Day1@data), value = T)
Pineal2_Day1.percent.mito <- Matrix::colSums(Pineal2_Day1@raw.data[Pineal2_Day1.mito.genes, ])/Matrix::colSums(Pineal2_Day1@raw.data)
Pineal2_Day1 <- AddMetaData(Pineal2_Day1, Pineal2_Day1.percent.mito, "percent.mito")
GenePlot(Pineal2_Day1, "nUMI","nGene")
VlnPlot(Pineal2_Day1, c("nUMI","nGene","percent.mito"),nCol=3, group.by = "orig.ident")
```

```{r Filter by nGene/nUMI, results="hold"}
GenePlot(Pineal2_Day1, "nUMI", "nGene")
#Pineal2_Day1 <- FilterCells(Pineal2_Day1, subset.names = "percent.mito", high.thresholds = 0.05)
Pineal2_Day1 <- FilterCells(Pineal2_Day1, subset.names = "nUMI", high.thresholds = 25000)

GenePlot(Pineal2_Day1, "nUMI","nGene")
VlnPlot(Pineal2_Day1, c("nUMI","nGene","percent.mito"),nCol=3)
```

```{r Log Normalize}
Pineal2_Day1 <- NormalizeData(Pineal2_Day1, scale.factor = 1e4, display.progress = F)
```

```{r Find Variable Genes, include=FALSE}
Pineal2_Day1 <- FindVariableGenes(Pineal2_Day1, x.low.cutoff = 0.0125, x.high.cutoff = 3, y.cutoff = 0.3, do.plot = F)
length(Pineal2_Day1@var.genes)
```

```{r Scale/Regress}
Pineal2_Day1 <- ScaleData(Pineal2_Day1, display.progress = F)
```

```{r PCA I, message=FALSE, warning=FALSE, include=FALSE}
Pineal2_Day1 <- RunPCA(Pineal2_Day1, pc.genes = Pineal2_Day1@var.genes, pcs.compute = 40, do.print = F)
Pineal2_Day1 <- ProjectPCA(Pineal2_Day1, do.print = F)
```
```{r PCA Plot I, echo=FALSE, message=FALSE, warning=FALSE}
PCAPlot(Pineal2_Day1, no.legend = T)
PCElbowPlot(Pineal2_Day1, num.pc = 50)
#JackStraw(Pineal2_Day1, num.pc = 30)
PCHeatmap(Pineal2_Day1, pc.use = 1:6, cells.use = 200, num.genes = 25, do.balanced = F)
PCHeatmap(Pineal2_Day1, pc.use = 7:12, cells.use = 150, num.genes = 25, do.balanced = T)
PCHeatmap(Pineal2_Day1, pc.use = 13:18, cells.use = 150, num.genes = 25, do.balanced = T)
```

```{r Clustering, echo=TRUE, message=FALSE, warning=FALSE}
Pineal2_Day1 <- FindClusters(Pineal2_Day1, dims.use = 1:16, reduction.type = "pca", resolution = 1.5, print.output = F, save.SNN = T)
```

```{r Generate TSNE, echo=TRUE, message=FALSE, warning=FALSE}
Pineal2_Day1 <- RunTSNE(Pineal2_Day1, dims.use = 1:16, do.fast = T)
```

```{r Plot TSNE, echo=FALSE, results="hide"}
Pineal2_Day1 <- BuildClusterTree(Pineal2_Day1, genes.use = Pineal2_Day1@var.genes, do.plot = T, do.reorder = T, reorder.numeric = T)
TSNEPlot(Pineal2_Day1, do.label = T, do.return = T) + ggtitle("PCs 1-16, 1.5 res")
FeaturePlot(Pineal2_Day1, "nUMI", cols.use = c("light grey","red"))
FeaturePlot(Pineal2_Day1, "nGene", cols.use = c("light grey","red"))
```

```{r Markers}
FeaturePlot(Pineal2_Day1, c("Tph1","Esm1","Apoe","Penk","Lum","Vwf","Sparcl1","Lyz2","C1qa","RT1-Bb"), cols.use=c("light grey","red"))
DotPlot(object = Pineal2_Day1, genes.plot = c("Tph1","Esm1","Apoe","Penk","Lum","Vwf","Sparcl1","Lyz2","C1qa","RT1-Bb"))
```

