---
title: "DK Pineal2 Day Combined 10X Seurat v2"
author: "Joseph Mays"
output:
  html_notebook: default
  html_document: default
  pdf_document: default
---

```{r Pineal2_Day1n2 Merge, results="hide"}
Pineal2_Day1n2 <- MergeSeurat(Pineal2_Day1, Pineal2_Day2, project = "Pineal2_Day1n2", add.cell.id1 = "D1", add.cell.id2 = "D2")
```

```{r QC stats}
Pineal2_Day1n2
GenePlot(Pineal2_Day1n2, "nUMI","nGene")
VlnPlot(Pineal2_Day1n2, c("nUMI","nGene","percent.mito"),nCol=3, group.by = "orig.ident")
```

```{r Filter by nGene/nUMI, results="hold"}
#GenePlot(Pineal2_Day1n2, "nUMI", "nGene")
#Pineal2_Day1n2 <- FilterCells(Pineal2_Day1n2, subset.names = "percent.mito", high.thresholds = 0.05)
#Pineal2_Day1n2 <- FilterCells(Pineal2_Day1n2, subset.names = "nUMI", high.thresholds = 25000)
#GenePlot(Pineal2_Day1n2, "nUMI","nGene")
#VlnPlot(Pineal2_Day1n2, c("nUMI","nGene","percent.mito"),nCol=3)
```

```{r Log Normalize}
#Pineal2_Day1n2 <- NormalizeData(Pineal2_Day1n2, scale.factor = 1e4, display.progress = F)
```

```{r Find Variable Genes, include=FALSE}
Pineal2_Day1n2 <- FindVariableGenes(Pineal2_Day1n2, x.low.cutoff = 0.0125, x.high.cutoff = 3, y.cutoff = 0.3, do.plot = F)
length(Pineal2_Day1n2@var.genes)
```

```{r Scale/Regress}
Pineal2_Day1n2 <- ScaleData(Pineal2_Day1n2, display.progress = F)
```

```{r PCA I, message=FALSE, warning=FALSE, include=FALSE}
Pineal2_Day1n2 <- RunPCA(Pineal2_Day1n2, pc.genes = Pineal2_Day1n2@var.genes, pcs.compute = 40, do.print = F)
Pineal2_Day1n2 <- ProjectPCA(Pineal2_Day1n2, do.print = F)
```
```{r PCA Plot I, echo=FALSE, message=FALSE, warning=FALSE}
PCAPlot(Pineal2_Day1n2, no.legend = T)
PCElbowPlot(Pineal2_Day1n2, num.pc = 50)
#JackStraw(Pineal2_Day1n2, num.pc = 30)
PCHeatmap(Pineal2_Day1n2, pc.use = 1:6, cells.use = 200, num.genes = 25, do.balanced = F)
PCHeatmap(Pineal2_Day1n2, pc.use = 7:12, cells.use = 150, num.genes = 25, do.balanced = T)
PCHeatmap(Pineal2_Day1n2, pc.use = 13:18, cells.use = 150, num.genes = 25, do.balanced = T)
```

```{r Clustering, echo=TRUE, message=FALSE, warning=FALSE}
#PC2 is driven by batch and is excluded
Pineal2_Day1n2 <- FindClusters(Pineal2_Day1n2, dims.use = c(1,3:6,9:20), reduction.type = "pca", resolution = 1.5, print.output = F, save.SNN = T)
```

```{r Generate TSNE, echo=TRUE, message=FALSE, warning=FALSE}
Pineal2_Day1n2 <- RunTSNE(Pineal2_Day1n2, dims.use = c(1,3:6,9:20), do.fast = T)
```

```{r Plot TSNE, echo=FALSE, results="hide"}
Pineal2_Day1n2 <- BuildClusterTree(Pineal2_Day1n2, genes.use = Pineal2_Day1n2@var.genes, do.plot = T, do.reorder = T, reorder.numeric = T)
TSNEPlot(Pineal2_Day1n2, do.label = T, do.return = T) + ggtitle("PCs 1-20, 1.5 res")
TSNEPlot(Pineal2_Day1n2, do.label = T, group.by = "orig.ident")
FeaturePlot(Pineal2_Day1n2, "nUMI", cols.use = c("light grey","red"))
FeaturePlot(Pineal2_Day1n2, "nGene", cols.use = c("light grey","red"))
```

```{r Markers}
FeaturePlot(Pineal2_Day1n2, c("Tph1","Asmt","Esm1","Apoe","Penk","Lum","Vwf","Sparcl1","Lyz2","C1qa","RT1-Bb"), cols.use=c("light grey","red"))
DotPlot(object = Pineal2_Day1n2, genes.plot = c("Tph1","Asmt","Esm1","Apoe","Penk","Lum","Vwf","Sparcl1","Lyz2","C1qa","RT1-Bb"))
```

```{r Cluster Rename}
Pineal2_Day1n2 <- RenameIdent(Pineal2_Day1n2, old.ident.name = 2, new.ident.name = "Penk/Esm1+ 1")
Pineal2_Day1n2 <- RenameIdent(Pineal2_Day1n2, old.ident.name = 3, new.ident.name = "Penk/Esm1+ 2")
Pineal2_Day1n2 <- RenameIdent(Pineal2_Day1n2, old.ident.name = 4, new.ident.name = "Penk/Esm1+ 3")
Pineal2_Day1n2 <- RenameIdent(Pineal2_Day1n2, old.ident.name = 1, new.ident.name = "Lum+")
Pineal2_Day1n2 <- RenameIdent(Pineal2_Day1n2, old.ident.name = 5, new.ident.name = "Lyz2+")
Pineal2_Day1n2 <- RenameIdent(Pineal2_Day1n2, old.ident.name = 6, new.ident.name = "High_Asmt_Tph1+")
Pineal2_Day1n2 <- MergeNode(Pineal2_Day1n2, 23)
Pineal2_Day1n2 <- RenameIdent(Pineal2_Day1n2, old.ident.name = 10, new.ident.name = "Tph1+")
TSNEPlot(Pineal2_Day1n2, do.label = T, do.return = T)
```

```{r Non-Pinealocyte}
Pineal2_Day1n2 <- StashIdent(Pineal2_Day1n2, "complete")
Pineal2_Day1n2_NonP <- SubsetData(Pineal2_Day1n2, ident.remove = c("Tph1+", "High_Asmt_Tph1+"))
TSNEPlot(Pineal2_Day1n2_NonP, do.label = T, do.return = T)

#Should the new set be rescaled?
```

```{r Find Variable Genes II, include=FALSE}
Pineal2_Day1n2_NonP <- FindVariableGenes(Pineal2_Day1n2_NonP, x.low.cutoff = 0.05, x.high.cutoff = 3, y.cutoff = 0.4, do.plot = F)
length(Pineal2_Day1n2_NonP@var.genes)
```

```{r PCA II, message=FALSE, warning=FALSE, include=FALSE}
Pineal2_Day1n2_NonP <- RunPCA(Pineal2_Day1n2_NonP, pc.genes = Pineal2_Day1n2_NonP@var.genes, pcs.compute = 40, do.print = F)
Pineal2_Day1n2_NonP <- ProjectPCA(Pineal2_Day1n2_NonP, do.print = F)
```
```{r PCA Plot II, echo=FALSE, message=FALSE, warning=FALSE}
PCAPlot(Pineal2_Day1n2_NonP, no.legend = T)
PCElbowPlot(Pineal2_Day1n2_NonP, num.pc = 50)
#JackStraw(Pineal2_Day1n2_NonP, num.pc = 30)
PCHeatmap(Pineal2_Day1n2_NonP, pc.use = 1:6, cells.use = 200, num.genes = 25, do.balanced = F)
PCHeatmap(Pineal2_Day1n2_NonP, pc.use = 7:12, cells.use = 150, num.genes = 25, do.balanced = T)
PCHeatmap(Pineal2_Day1n2_NonP, pc.use = 13:18, cells.use = 150, num.genes = 25, do.balanced = T)
```

```{r Clustering II, echo=TRUE, message=FALSE, warning=FALSE}
Pineal2_Day1n2_NonP <- FindClusters(Pineal2_Day1n2_NonP, dims.use = c(1:11), reduction.type = "pca", resolution = 2.0, print.output = F, save.SNN = T)
```

```{r Generate TSNE II, echo=TRUE, message=FALSE, warning=FALSE}
Pineal2_Day1n2_NonP <- RunTSNE(Pineal2_Day1n2_NonP, dims.use = c(1:11), do.fast = T)
```

```{r Plot TSNE II, echo=FALSE, results="hide"}
Pineal2_Day1n2_NonP <- BuildClusterTree(Pineal2_Day1n2_NonP, genes.use = Pineal2_Day1n2_NonP@var.genes, do.plot = T, do.reorder = T, reorder.numeric = T)
TSNEPlot(Pineal2_Day1n2_NonP, do.label = T, do.return = T) + ggtitle("PCs 1-11, 1.5 res")
TSNEPlot(Pineal2_Day1n2_NonP, do.label = T, group.by = "orig.ident")
TSNEPlot(Pineal2_Day1n2_NonP, do.label = T, group.by = "complete")
FeaturePlot(Pineal2_Day1n2_NonP, "nUMI", cols.use = c("light grey","red"))
FeaturePlot(Pineal2_Day1n2_NonP, "nGene", cols.use = c("light grey","red"))
```

```{r Markers II}
FeaturePlot(Pineal2_Day1n2_NonP, c("Tph1","Asmt","Esm1","Apoe","Penk","Lum","Vwf","Sparcl1","Lyz2","C1qa","RT1-Bb"), cols.use=c("light grey","red"))
DotPlot(object = Pineal2_Day1n2_NonP, genes.plot = c("Tph1","Asmt","Esm1","Apoe","Penk","Lum","Vwf","Sparcl1","Lyz2","C1qa","RT1-Bb"))
```


```{r}
#KleinConvert(SeuratObject = Pineal2_Day1n2, matrix.type = "unscaled", output.filename = "Day1n2_normalized_counts_090517.txt")
```

