---
title: "PinealGland Sample Day_2 Seurat_3.0.0"
author: "Joseph Mays"
output:
  html_notebook: default
  html_document: default
  pdf_document: default
---

Import Filtered Barcodes from CellRanger. Filter out cells with less than 800 genes and genes represented in less than 2 cells.
```{r Pineal2_Day2 Import, message=FALSE, warning=FALSE, results="hide"}
Pineal2_Day2.matrix <- Read10X(data.dir = "./OriginalReferenceFilteredMatrix/Day2/")
Pineal2_Day2 <- CreateSeuratObject(Pineal2_Day2.matrix, project = "Pineal2_Day2", min.cells = 3, min.features = 800)
```

```{r}
print(paste(dim(Pineal2_Day2.matrix)[2] - dim(GetAssayData(Pineal2_Day2, slot = "counts"))[2], " cells were filtered from the original matrix.", sep=''))
```

Calculate percent expression of mitochondrial genes, output QC plots. 
```{r QC stats}
# The MetadataInit function adds barcode and arbitrary cell ID columns to the metadata table in the Seurat Object 
Pineal2_Day2 <- MetadataInit(Pineal2_Day2, ID.prefix = "Day1")
Pineal2_Day2.mito.genes <- grep("^Mt-", rownames(Pineal2_Day2), value = T)
Pineal2_Day2.percent.mito <- Matrix::colSums(GetAssayData(Pineal2_Day2, slot = "counts", assay = "RNA")[Pineal2_Day2.mito.genes, ])/Matrix::colSums(GetAssayData(Pineal2_Day2, slot = "counts", assay = "RNA"))
Pineal2_Day2$percent.mito <- Pineal2_Day2.percent.mito
FeatureScatter(Pineal2_Day2, "nCount_RNA","nFeature_RNA")
VlnPlot(Pineal2_Day2, features = c("nCount_RNA","nFeature_RNA","percent.mito"), ncol=3, group.by = "orig.ident", pt.size = 0)
```
Filter cells, cutoffs based on QC plots. 
```{r Filter by nGene/nUMI, results="hold"}
FeatureScatter(Pineal2_Day2, "nCount_RNA","nFeature_RNA")
Pineal2_Day2 <- subset(Pineal2_Day2, subset = nCount_RNA < 35000)
FeatureScatter(Pineal2_Day2, "nCount_RNA","nFeature_RNA")
VlnPlot(Pineal2_Day2, features = c("nCount_RNA","nFeature_RNA","percent.mito"), ncol=3, group.by = "orig.ident", pt.size = 0)
```

```{r Log Normalize}
Pineal2_Day2 <- NormalizeData(Pineal2_Day2, scale.factor = 1e4, verbose = F, normalization.method = "LogNormalize")
```

```{r Find Variable Genes, echo=TRUE}
Pineal2_Day2 <- FindVariableFeatures(Pineal2_Day2, selection.method = "mean.var.plot", mean.cutoff = c(0.0125,3), dispersion.cutoff = c(0.3,Inf), verbose = F, do.plot=F)
print(paste(length(VariableFeatures(Pineal2_Day2)), " variable genes selected.", sep=""))
```

```{r Scale/Regress}
Pineal2_Day2 <- ScaleData(Pineal2_Day2,verbose = F)
```

```{r PCA I, echo=TRUE, message=FALSE, warning=FALSE}
Pineal2_Day2 <- RunPCA(Pineal2_Day2, npcs = 40, verbose = F)
Pineal2_Day2 <- ProjectDim(Pineal2_Day2, verbose = F)
```
```{r PCA Plot I, echo=TRUE, message=FALSE, warning=FALSE}
PCAPlot(Pineal2_Day2, no.legend = T)
ElbowPlot(Pineal2_Day2, ndims = 40)
DimHeatmap(Pineal2_Day2, dims = 1:6)
DimHeatmap(Pineal2_Day2, dims = 7:12, balanced = T)
DimHeatmap(Pineal2_Day2, dims = 13:18, balanced = T)
```

PCs selected for generating TSNE plot. Number of PCs and resolution parameters will be refined after combining samples.
```{r Clustering, echo=TRUE, message=FALSE, warning=FALSE}
Pineal2_Day2 <- FindNeighbors(Pineal2_Day2, dims = 1:12, reduction = "pca", do.plot = T)
Pineal2_Day2 <- FindClusters(Pineal2_Day2, resolution = 1.5, verbose = F)
```

```{r Generate TSNE, echo=TRUE, message=FALSE, warning=FALSE}
Pineal2_Day2 <- RunTSNE(Pineal2_Day2, dims = 1:12)
```

```{r Plot TSNE, echo=TRUE, message=FALSE, warning=FALSE, results="hide"}
Pineal2_Day2 <- BuildClusterTree(Pineal2_Day2, reorder = T, reorder.numeric = T)
PlotClusterTree(Pineal2_Day2)
TSNEPlot(Pineal2_Day2, do.label = T, do.return = T) + ggtitle("PCs 1-12, 1.5 res")
FeaturePlot(Pineal2_Day2, "nCount_RNA", cols = c("light grey","red"))
FeaturePlot(Pineal2_Day2, "nFeature_RNA", cols = c("light grey","red"))
```

```{r Markers}
FeaturePlot(Pineal2_Day2, c("Tph1","Esm1","Apoe","Penk","Lum","Vwf","Sparcl1","Lyz2","C1qa","RT1-Bb"), cols=c("light grey","red"))
DotPlot(object = Pineal2_Day2, features = c("Tph1","Esm1","Apoe","Penk","Lum","Vwf","Sparcl1","Lyz2","C1qa","RT1-Bb")) + theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

```{r}
sessionInfo()
```