---
title: "Pineal Gland Experiment 2 - Night"
author: "Joseph Mays"
output:
  html_notebook: 
      toc: true
      toc_depth: 2
      toc_float:
        collapsed: false
  html_document: 
    toc: true
    toc_depth: 2
  pdf_document: default
---

Two Night Samples, 10X Genomics 3'; Seurat v2.2.0

# Setup
## Merge Original Seurat Objects
```{r Pineal2_Night1n2 Merge, echo=TRUE, message=FALSE, warning=FALSE, results="hide"}
Pineal2_Night1n2 <- MergeSeurat(Pineal2_Night1, Pineal2_Night2, project = "Pineal2_Night1n2", add.cell.id1 = "N1", add.cell.id2 = "N2")
#Doublets previously identified are removed here 
load("./master.doublets.night.Robj")
Pineal2_Night1n2@meta.data$treatment <- "Night"
Pineal2_Night1n2 <- SubsetData(Pineal2_Night1n2, cells.use = setdiff(colnames(Pineal2_Night1n2@data),master.doublets.night))
Pineal2_Night1n2 <- ScaleData(Pineal2_Night1n2, display.progress = F)
```

## QC Stats
```{r QC stats}
Pineal2_Night1n2
GenePlot(Pineal2_Night1n2, "nUMI","nGene")
VlnPlot(Pineal2_Night1n2, c("nUMI","nGene","percent.mito"),nCol=3, group.by = "orig.ident", x.lab.rot = T, size.x.use = 12)
```
# Dimensional Reduction - All Cells
## Identify Highly Variable Genes
```{r Find Variable Genes, echo=TRUE, message=FALSE, warning=FALSE, results='hide'}
Pineal2_Night1n2 <- FindVariableGenes(Pineal2_Night1n2, x.low.cutoff = 0.0125, x.high.cutoff = 3, y.cutoff = 0.35, do.plot = F)
print(paste(length(Pineal2_Night1n2@var.genes), " variable genes selected.", sep=""))
```

## Principal Components Analysis 
```{r PCA I, message=FALSE, warning=FALSE}
Pineal2_Night1n2 <- RunPCA(Pineal2_Night1n2, pc.genes = Pineal2_Night1n2@var.genes, pcs.compute = 40, do.print = F)
Pineal2_Night1n2 <- ProjectPCA(Pineal2_Night1n2, do.print = F)
```
```{r PCA Plot I, message=FALSE, warning=FALSE}
PCAPlot(Pineal2_Night1n2, no.legend = T)
PCElbowPlot(Pineal2_Night1n2, num.pc = 40)
PCHeatmap(Pineal2_Night1n2, pc.use = 1:6, cells.use = 200, num.genes = 25, do.balanced = F)
PCHeatmap(Pineal2_Night1n2, pc.use = 7:12, cells.use = 150, num.genes = 25, do.balanced = T)
PCHeatmap(Pineal2_Night1n2, pc.use = 13:18, cells.use = 150, num.genes = 25, do.balanced = T)
```
## tSNE Projection
```{r Clustering, echo=TRUE, message=FALSE, warning=FALSE}
cluster.dims <- c(1:11)
cluster.res <- 1.5
Pineal2_Night1n2 <- FindClusters(Pineal2_Night1n2, dims.use = cluster.dims, reduction.type = "pca", resolution = cluster.res, print.output = F, save.SNN = T)
```

```{r Generate TSNE, echo=TRUE, message=FALSE, warning=FALSE}
Pineal2_Night1n2 <- RunTSNE(Pineal2_Night1n2, dims.use = cluster.dims, do.fast = T)
```

```{r Plot TSNE, echo=TRUE, message=FALSE, warning=FALSE, results="hide"}
Pineal2_Night1n2 <- BuildClusterTree(Pineal2_Night1n2, genes.use = Pineal2_Night1n2@var.genes, do.plot = T, do.reorder = T, reorder.numeric = T)
TSNEPlot(Pineal2_Night1n2, do.label = T, do.return = T) + ggtitle(paste("Night1n2, PCs ", cluster.dims[1],"-",length(cluster.dims),", res = ", cluster.res, sep=''))
TSNEPlot(Pineal2_Night1n2, do.label = T, group.by = "orig.ident")
FeaturePlot(Pineal2_Night1n2, "nUMI", cols.use = c("light grey","red"))
FeaturePlot(Pineal2_Night1n2, "nGene", cols.use = c("light grey","red"))
```
## Cluster Identification by Markers
```{r Markers}
FeaturePlot(Pineal2_Night1n2, c("Tph1","Asmt","Esm1","Apoe","Penk","Lum","Vwf","Lyz2","C1qa","RT1-Bb"), cols.use=c("light grey","red"))
DotPlot(object = Pineal2_Night1n2, genes.plot = c("Tph1","Asmt","Esm1","Apoe","Penk","Lum","Vwf","Lyz2","C1qa","RT1-Bb", "S100b"))
```
### Rename Clusters
```{r Cluster Rename}
Pineal2_Night1n2 <- RenameIdent(Pineal2_Night1n2, old.ident.name = 4, new.ident.name = "Penk 1")
Pineal2_Night1n2 <- RenameIdent(Pineal2_Night1n2, old.ident.name = 5, new.ident.name = "Penk 2")
Pineal2_Night1n2 <- RenameIdent(Pineal2_Night1n2, old.ident.name = 3, new.ident.name = "Penk 3")
Pineal2_Night1n2 <- RenameIdent(Pineal2_Night1n2, old.ident.name = 6, new.ident.name = "Lum")
Pineal2_Night1n2 <- RenameIdent(Pineal2_Night1n2, old.ident.name = 2, new.ident.name = "C1qa")
Pineal2_Night1n2 <- RenameIdent(Pineal2_Night1n2, old.ident.name = 1, new.ident.name = "RT1-Bb")
Pineal2_Night1n2 <- RenameIdent(Pineal2_Night1n2, old.ident.name = 7, new.ident.name = "High_Asmt_Tph1")
#Vwf+ cells isolated manually from the Lum+ group
load("./Vwf.Night.Robj")
Pineal2_Night1n2 <- SetIdent(Pineal2_Night1n2, cells.use = Vwf.Night, ident.use = "Vwf")
Pineal2_Night1n2 <- MergeNode(Pineal2_Night1n2, 26)
Pineal2_Night1n2 <- RenameIdent(Pineal2_Night1n2, old.ident.name = 10, new.ident.name = "Tph1")
Pineal2_Night1n2@ident = factor(Pineal2_Night1n2@ident,levels(Pineal2_Night1n2@ident)[c(3,1,5,6,7,2,8,4,9)])
TSNEPlot(Pineal2_Night1n2, do.label = T, do.return = T)
```

```{r}
sessionInfo()
```